run:
  go: '1.18'
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - test # no lints for tests
  skip-files:
    - .*_test.go$ # unit tests
    - transport/ws/intercepting_writer.go # code from http package of go-kit project (https://github.com/go-kit/kit/blob/master/transport/http/intercepting_writer.go).
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable:
    - exhaustruct
    - exhaustivestruct
    - varcheck
    - varnamelen
    - gochecknoglobals
    - goconst
    - godot
    - godox
    - golint
    - interfacer
    - deadcode
    - maligned
    - structcheck
    - ifshort
    - nosnakecase
    - nonamedreturns
    - nlreturn
    - scopelint
    - wsl
    - wrapcheck
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused

linters-settings:
  exhaustive:
    ignore-enum-members: '^*(Unspecified|Undefined|Unknown|Idle)$'
  cyclop:
    max-complexity: 20
  gomnd:
    ignored-numbers:
      - '2'
      - '4'
      - '8'
      - '16'
      - '32'
      - '64'
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/einouqo/ext-kit) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake

issues:
  exclude-rules:
    - linters:
        - wrapcheck
      text: 'error returned from interface method should be wrapped'
      source: ^*return .*
    - linters:
        - wrapcheck
      text: ^error returned from external package is unwrapped[:] .*multierror.* error$
    - linters:
        - wrapcheck
      source: .*status.Error\(.*, .*\).*
    - linters:
        - cyclop
      text: 'calculated cyclomatic complexity for function'
      source: ^func \(.*\) String\(\) string {$
    - linters:
        - gomnd
      source: .*(time\..|[0-9]+<<[0-9]+)*$
    - linters:
        - gofumpt
      source: ^var \(
    - linters:
        - unparam
      # except setters with self returning
      text: .*\)\.set([A-z0-9]+)? - result 0 \(\*.*\) is never used$
    - linters:
        - gosec
      text: 'G109:'
    - linters:
        - gosec
      text: 'G404:'
    - linters:
        - lll
      source: .*// .*
    - linters:
        - stylecheck
      text: 'ST1012:'
    - linters:
        - forbidigo
      text: use of `fmt\..*` forbidden by pattern `.*`$
    - path: transport # ok for transport
      linters: [ gocognit, gocyclo, cyclop, forcetypeassert, funlen, ireturn, lll ]
    - path: endpoint
      linters: [ errname, revive ]
    - linters:
        - gocritic
      text: 'appendAssign: append result not assigned to the same slice'
    - linters:
        - errcheck
      source: ^\s*defer .*$


