version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  exclusions:
    rules:
      # an exception, as the error value is used to signal the end of the stream
      - linters:
          - staticcheck
        source: "StreamDone"
      # as documentation states: "... This method always returns a nil error" https://github.com/grpc/grpc-go/blob/v1.78.0/stream.go#L105-L108
      - linters:
          - errcheck
        source: "defer .*\\.CloseSend()"

